name: Upload release

env:
  SPACEDOCK_MOD_ID: 3359 # Flight Plan

on:
  release:
    types: [ "published" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Download NuGet
        id: download-nuget
        run: sudo curl -o /usr/local/bin/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0

      - name: Check version
        run: |
          version=$(jq -r '.version' plugin_template/swinfo.json)
          echo "Tag is ${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" != "$version" ]];
          then
            echo "Invalid version tag: ${{ github.ref_name }}. Expected $version."
            exit 1
          fi

      - name: Build the solution
        run: dotnet build "FlightPlan.sln" -c Release

      - name: Extract current version
        id: get-version
        run: |
          version=$(jq -r '.version' plugin_template/swinfo.json)
          echo "Version is $version"
          echo "version=$version" >> $GITHUB_ENV
          echo "release_filename=flight_plan-$version.zip" >> $GITHUB_ENV
          echo "zip=$(ls -1 dist/flight_plan-*.zip | head -n 1)" >> $GITHUB_ENV
          echo "upload_url=$(wget -qO- https://api.github.com/repos/$GITHUB_REPOSITORY/releases | jq '.[0].upload_url' | tr -d \")" >> $GITHUB_ENV
          wget -qO- https://api.github.com/repos/$GITHUB_REPOSITORY/releases | jq -r '.[0].body' > ./changelog.md

      - name: Upload zip to release
        uses: shogo82148/actions-upload-release-asset@v1.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: ${{ env.zip }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

      - name: Add Mask
        run: echo "::add-mask::${{ secrets.SPACEDOCK_PASSWORD }}"

      - name: Update mod on SpaceDock
        uses: KSP2Community/spacedock-upload@v1.0.0
        with:
          username: ${{ secrets.SPACEDOCK_USER }}
          password: ${{ secrets.SPACEDOCK_PASSWORD }}
          game_id: 22407
          mod_id: ${{ env.SPACEDOCK_MOD_ID }}
          version: ${{ env.version }}
          zipball: ${{ env.zip }}
          changelog: ./changelog.md
          
      - name: Update mod topic
        uses: Kerbalight/ksp2-forum-post-action@latest
        with:
          username: ${{ secrets.KSP_FORUM_USERNAME }}
          password: ${{ secrets.KSP_FORUM_PASSWORD }}
          post_title: "## Release {version}" # (without the v)
          forum_topic_url: https://forum.kerbalspaceprogram.com/topic/216393-flight-plan-0100/
          forum_topic_title: "Flight Plan [{version} for KSP2 v{ksp2_version}+]"
          spacedock_url: "https://spacedock.info/mod/3359/Flight%20Plan#changelog"
          version: ${{ env.version }}
          changelog: ./changelog.md
